# Use root/example as user/password credentials
version: '3.1'

services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000

  db:
    image: mariadb
    restart: always
    depends_on:
      nginx:
        condition: service_started
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: buju

  adminer:
    image: adminer
    restart: always
    depends_on:
      nginx:
        condition: service_started

  node:
    image: node:lts
    restart: always
    working_dir: /buju-api
    volumes:
    - ./:/buju-api
    container_name: nodejs
    depends_on:
      db:
        condition: service_started
      nginx:
        condition: service_started
    command: bash -c "cd buju-api && npm i && node app.js"

  frontend:
    image: node:lts
    restart: always
    working_dir: /buju-frontend
    volumes:
      - ./:/buju-frontend
    container_name: buju-frontend
    depends_on:
      nginx:
        condition: service_started
    command: bash -c "cd buju-frontend && npm i && npm run serve -- --port 8081"

