# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: buju

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node:
    image: node:lts
    restart: always
    working_dir: /buju-api
    volumes:
    - ./:/buju-api
    container_name: nodejs
    depends_on:
      db:
        condition: service_started
    ports:
    - 3000:3000
    command: bash -c "cd buju-api && npm i && node app.js"

  frontend:
    image: node:lts
    restart: always
    working_dir: /buju-frontend
    volumes:
      - ./:/buju-frontend
    container_name: buju-frontend
    ports:
      - 8081:8081
    command: bash -c "cd buju-frontend && npm i && npm run serve -- --port 8081"

